---
openapi: 3.0.1
info:
  title: Location API
  version: v1
paths:
  "/api/coordinates/search":
    parameters:
    - in: query
      name: location
      schema:
        type: string
      description: The location name or address
      required: true
    get:
      summary: Search location coordinates
      tags:
      - Location coordinates
      produces:
      - application/json
      security:
      - bearerAuth: []
      responses:
        '200':
          description: location found
        '422':
          description: location not found
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    bearer:
      type: bearer
      name: Authorization
      in: header
security:
  bearerAuth: []
