default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  user: postgres
# password: your_db_password
# port: 5432
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: location_api_development

test:
  <<: *default
  database: location_api_test

production:
  <<: *default
  database: location_api_production
  username: location_api
  password: <%= ENV['LOCATION_API_DATABASE_PASSWORD'] %>